### PR TITLE
Fix/disable access 4 user not loggedin

### PR DESCRIPTION
**Pull request by ycliuhw**
even read access should not allow for non authenticated users.

### CODE REVIEW

**Comment by tboerger** [comment]
If I see it correctly you always hide the builds if a user is not logged in? If so this is wrong behavior. Generally builds are visible for anonymous users, except for private repositories.

**Comment by ycliuhw** [comment]
Hi @tboerger
The reason why I have this PR is I found the helm plugin logs all the global environment variables includes alll credentials(k8s cluster token for example). 
But if this is the expected behaviour for public repo, I am not sure we can hide credentials like *** when we stream the log to frontend page?

**Comment by ycliuhw** [comment]
I think drone is really a well designed and modern replacement for Jenkins for containers. And I want to contribute to this project when I have time. But I am not sure if we have a roadmap for this ui repo already or not coz I saw there are a few different exp branch for vue etc. and also the master react branch doesn’t use redux etc data store.

**Comment by tboerger** [comment]
It's up to the plugin to not printing secrets, drone doesn't know what is secure and what not

**Comment by bradrydzewski** [comment]
I am going to close this pull request because drone is behaving as intended. I would recommend that you instead consider sending a patch to the helm plugin so that it does not print sensitive data to the console. Cheers

**Pull request closed without merging**
