### PR TITLE
Show no repos enabled if results have returned with nothing

### PR DESCRIPTION
**Pull request by josmo**
if no repos are enabled it leaves Loading up.  This will show a diff notification while loading vs none being enabled.

### CODE REVIEW

**Comment by bradrydzewski** [comment]
We have a `loading` parameter in the tree that is intended for this purpose, but was never hooked up. If loading is false and the list is empty, it would be used to display an empty message.

**Comment by josmo** [comment]
sounds good. I'm not exactly sure how the implementation should look like.  I'll take a look but if you have a quick suggestion I'll definitely appreciate it.

**Comment by josmo** [comment]
@bradrydzewski updated to use the loading property. Let me know if that works for you.

**Comment by josmo** [comment]
@bradrydzewski Just wanted to check in on this, if I used the correct property this time?

**Pull request merged**
