### PR TITLE
Mobile mode fixes

### PR DESCRIPTION
**Pull request by cyberb**
Little improvement to make mobile usable comparing to current state.
Tried not to break desktop mode, but minor layout change is possible.

1. Auto hide menu (currently it hides everything anyway)
2. Show everything vertically (flex-flow: row wrap)

Please let me know if I broke something.

### CODE REVIEW

**Comment by cyberb** [comment]
screenshot_20171107-083301

screenshot_20171107-083311

screenshot_20171107-083320

**Comment by cyberb** [comment]
Any updates?

**Comment by serverwentdown** [comment]
amazing, gonna use this patch internally while the interface gets merged.

**Comment by frebib** [comment]
Is it possible to open the left-hand menu up whilst in mobile mode?

I think it would be good to unconstrain the 'details' section of the build view as on my phone it doesn't render to the full page width:

**Comment by cyberb** [comment]
For left menu unfortunately you need to enable desktop mode in the browser. All we need is actually a button open/close menu which does not exist yet as i know :(

For the details view as I remember I tried to unconstrain it so it takes the full width on mobile screen but then it does the same on desktop mode pushing build logs below.
I guess you can fix this by having uncontraint width only in mobile mode.

Yoi just need to open a browser and try things in f12 :)

**Comment by cyberb** [comment]
@bradrydzewski Am I right that this PR was not merged? Any reason why?

**Comment by bradrydzewski** [comment]
@cyberb a redesigned user interface was introduced in Oct 2018 just a few days after this pull request was opened. The new user interface superseded this pull request.

**Pull request closed without merging**
