### PR TITLE
bump dependencies

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by bradrydzewski** [comment]
@PeterDaveHello this project is not well tested, so I'm a bit hesitant to bump versions unless it fixes existing issues. Without good automated testing, unfortunately, bumping versions could introducing new bugs :(

**Comment by PeterDaveHello** [comment]
Oh okay, I thought the tests and build process are reliable enough until you tell me :)

**Comment by tboerger** [comment]
That would require a test suite first.

**Comment by bradrydzewski** [comment]
I'm going to close and re-bump once we have better testing in place. Thanks though!!

**Pull request closed without merging**
