### PR TITLE
Add LESS linter

### PR DESCRIPTION
**Pull request by mavimo**

### CODE REVIEW

**Comment by mavimo** [comment]
52 warning need to be fixed..

**Comment by bradrydzewski** [comment]
thanks!  I plan on merging this after 0.8 is tagged, which will be later today or early tomorrow.

**Comment by mavimo** [comment]
@bradrydzewski good!
After that I see some refactoring that should help styling (eg: const for fonts and component size (padding & c); do you have some plan/agree on PR that introduce a fake API server for frontend development?

**Comment by mavimo** [comment]
@bradrydzewski I completed all checks on this task, can you check it and maybe merge if it's ok?

 - linted all LESS files
 - move ANSI css file outside drone so we can replace it easly
 - checked all pages (repo build list, single build, settings, ...)

I suppose all work fine, let me know if you need some more rework

**Comment by bradrydzewski** [comment]
> move ANSI css file outside drone so we can replace it easily

can we move this to a separate pull request to discuss?

**Comment by mavimo** [comment]
@bradrydzewski initial codebase include styles from ANSI lib into `src/screens/repo/screens/build/logs/components/term.less`, this mean we are merging drone codebase with vendor.

Since there is a comment to do not alterate ANSI codebase I suppose we will like to replace/update it when needed, in order to isolate this component I move ANSI CSS into `src/shared/styles/ansi.less` file and excluded it from LESS linting; `term.less` include this file as dependency.

**Comment by mavimo** [comment]
@bradrydzewski I know you're hardly working on drone/drone, but any feedback on it? I have some improvement/fixes but if possible I'll prefer to work on it after this PR will be merged..

**Comment by mavimo** [comment]
@bradrydzewski up :)

**Comment by bradrydzewski** [comment]
sorry for the delay, and thanks for all your help

**Pull request merged**
