### PR TITLE
(bugfix) render logs if there is an error on build screen

### PR DESCRIPTION
**Pull request by tphoney**

### CODE REVIEW

**Comment by jvrplmlmn** [comment]
@tphoney for my own understanding, would this provide additional context in scenarios like

image

?

**Comment by tphoney** [comment]
from what i remember, yes it does.

**Comment by jvrplmlmn** [comment]
Nice! Getting this patch in would be really useful for us 😃

**Comment by d1wilko** [comment]
this bug will be fixed by this PR - https://github.com/drone/drone-ui/pull/365

I'm going to close this PR

**Pull request closed without merging**
