### PR TITLE
adding login button to the top right corner of the UI when logged out

### PR DESCRIPTION
**Pull request by dvmorris**

### CODE REVIEW

**Comment by tboerger** [comment]
Do you have a screenshot?

**Comment by dvmorris** [comment]
No, I don't actually know how to run this locally.

**Comment by tboerger** [comment]
It's described in the readme how to launch the ui, you just need to point it to some drone server

**Comment by dvmorris** [comment]
Oh OK, I will try that today and upload a screenshot.

**Comment by dvmorris** [comment]
So, I got it running locally, but it seems that everything is hard-coded to always stay logged in. And there is no route defined for the logout button, and it's currently generating a javascript error in the console.

**Comment by jhasse** [comment]
When running the UI via `npm start` one has to provide the auth token and this does result in always being logged in :/

**Pull request closed without merging**
