### PR TITLE
Adds a message when user has not added any repositories yet

### LINKED ISSUE #51: Sidebar showing "loading..." if feed is empty
The sidebar in the dashboard shows a "Loading..." message if the feed is empty (length == 0).
The message is wrong. Is definitely not loading. I think it should show a more relevant message. Like suggesting to enable some projects with possibly a link to the relevant page.

### PR DESCRIPTION
**Pull request by gillesdemey**
screen shot 2016-09-24 at 20 50 26

fixes #51

### CODE REVIEW

**Comment by tboerger** [comment]
This phrase is not entirely correct, it's also getting displayed if repos are activated but don't have a build yet. Otherwise lgtm

**Comment by gillesdemey** [comment]
> This phrase is not entirely correct

Sure, just let me know what you'd like it to say :)

> it's also getting displayed if repos are activated but don't have a build yet

Wasn't able to reproduce this by adding a repo without a build, are you sure the length of `feed` would still be 0?

**Comment by tboerger** [comment]
Yes I'm sure it will stay 0, but maybe brad is fine with it like it is.

**Comment by gillesdemey** [comment]
I've noticed that it's briefly shown while data is being fetched from the API, I'm assuming that's what you meant.

Definitely not a great experience, it would probably make sense to introduce a `loading` property to the state of the sidebar.

Is this something we should attach to this PR or do we introduce it later?

**Comment by bradrydzewski** [comment]
there is a loading field here that you might be able to use:
https://github.com/drone/drone-ui/blob/master/src/actions/tree.js#L67

**Comment by bradrydzewski** [comment]
also we don't really use the blue button anywhere in the application, so it doesn't really fit the existing style. Let's instead mirror the same style below (gray text with dark link)

screen shot 2016-09-24 at 3 18 38 pm

**Comment by gillesdemey** [comment]
I've addressed some of the concerns, PTAL :)

**Comment by jadengore** [comment]
Any update on this?

**Comment by bradrydzewski** [comment]
#88 was merged and fixes this. Thanks!

**Pull request closed without merging**
