### PR TITLE
Add agent to docker-compose.yml

### PR DESCRIPTION
**Pull request by choffmeister**
So that jobs will actually run.

### CODE REVIEW

**Comment by MetalMatze** [comment]
LGTM, but not tested.

**Comment by choffmeister** [comment]
@bradrydzewski Seems to be fine with it. He already rebase on this commit 😄

**Comment by choffmeister** [comment]
Oh stop, now his branch is orphan again

**Comment by bradrydzewski** [comment]
this branch is not being used. I'm using the `baobob` branch going forward

**Pull request closed without merging**
