### PR TITLE
Alternate build history item description based on event type

### PR DESCRIPTION
**Pull request by marcinc**
This PR addresses issue #46.

### CODE REVIEW

**Comment by bradrydzewski** [comment]
excellent. I think there are just some minor eslint errors, but will merge right away once resolved. Thanks so much!

**Comment by marcinc** [comment]
@bradrydzewski yes, should have checked that before PR. Fixed now.

**Comment by tboerger** [comment]
LGTM

**Comment by marcinc** [comment]
@bradrydzewski I guess this is now good to merge. It'd be good to get #62 in as well.

**Pull request merged**
