### PR TITLE
Move restart & cancel to build screen

### LINKED ISSUE #187: Move the restart build button out of the hamburger menu
moved from https://github.com/drone/drone/issues/2278

> The restart build button is in a very unintuitive location at present.
>
> Discussed on https://discourse.drone.io/t/drone-0-8-no-restart-button/908

### PR DESCRIPTION
**Pull request by iterion**
Fixes #187 

I've moved the restart and cancel button on to the build screen. It works for the cases I've tested, but I'm sure there are cases I've missed. I'm new to react so please let me know if I can accomplish things in a more canonical way.

### CODE REVIEW

**Comment by bryanhelmig** [comment]
👍  Seems like a quick and easy addition!

**Comment by ylecuyer** [comment]
@bradrydzewski what are you waiting for review or merge this request ?

**Comment by tboerger** [comment]
I'm pretty sure others would welcome some before/after screenshots attached to pull requests like that ;)

**Comment by ylecuyer** [comment]
@tboerger there you have : 

drone-cancel-btn
drone-cancel-hamburger
drone-restart-btn
drone-restart-hamburger

**Comment by ylecuyer** [comment]
@bradrydzewski @tboerger do you need something more ?

**Comment by ylecuyer** [comment]
ping @bradrydzewski @tboerger

**Comment by tboerger** [comment]
The button doesn't really look like a good button for me, but in the end it's the decision of @bradrydzewski

**Comment by ylecuyer** [comment]
@tboerger please explain further why it doesn't look like a good button.

@bradrydzewski is playing dead here answer and all other chanels except this one...

**Comment by jimthedev** [comment]
Hi all, is there anything I can do to help get this merged? Rebuild buried in the hamburger menu is driving us all a bit nuts.

**Comment by bradrydzewski** [comment]
there are no immediate plans for design or layout changes in the upcoming 0.9 release. All visual changes will likely get pushed to 0.10. I will update all relevant issues when there is something further to discuss.

**Pull request closed without merging**
